### ISSUE TITLE
The Sign-in is taking place without checking from database if the username exists.

### ISSUE THREAD

**Issue by axelonet** [Axelonet/PHPprofile#1]
If a random username and password are entered in the sign-in box, the user is able to start a session which shouldn't happen.

**Comment by axelonet** [comment]
@sumitdas9234 
Well, after changing the way of calling to num_rows in controller.php, the correct credentials are also not giving access to the next page. Its just redirecting all requests back to index irrespective of username and password.

**Comment by sumitdas9234** [comment]
Then you must check the queries and the data entries. The logic seems fine to me. I'll be testing your module tomorrow.
